### PR TITLE
Fix #34

### LINKED ISSUE #34: [regression] contacts list stays empty
Screenshot 2023-01-11 at 12 56 57
Screenshot 2023-01-11 at 12 56 43

### PR DESCRIPTION
**Pull request by michielbdejong**
Fixes the issue about contacts not showing up, but still leaving #36 as a follow-up issue.

Here's a screenshot from the fix-34 branch:

Screenshot 2023-01-11 at 13 03 26

### CODE REVIEW

**Comment by parhamin2010** [comment]
Fix added here
https://github.com/pondersource/oc-sciencemesh/pull/37/

**Review by parhamin2010 — APPROVED** [review]

**Review by parhamin2010 — COMMENTED** [review]
Ahh. I see. I added the accept route by mistake here. idk why!!!
I replaced the code in last commit here
https://github.com/pondersource/oc-sciencemesh/pull/37/commits/102653186fab85f61c73555d77fc797f8f5481cf

**Comment by michielbdejong** [comment]
@parhamin2010 I think your last two comments were about #37, not about this PR, right?

**Comment by parhamin2010** [comment]
@michielbdejong Yes correct.

**Pull request merged**
