### PR TITLE
frontend modification

### PR DESCRIPTION
**Pull request by parhamin2010**

### CODE REVIEW

**Comment by parhamin2010** [comment]
Hi Michiel,
Yes sure. I'll send you tomorrow at first.
Thanks.

**Comment by michielbdejong** [comment]
OK, I was waiting for @navid-dada to review this PR but the screenshots @parhamin2010 sent me via private email look good so let's merge!

@parhamin2010 will you make the same changes on https://github.com/pondersource/nc-sciencemesh?

**Comment by michielbdejong** [comment]
Here are the nc-sciencemesh screenshots:
image (2)
image (4)
image (3)

**Comment by parhamin2010** [comment]
@michielbdejong All of them are done on NC and OC.

**Pull request merged**
